# Site settings
# YAML cheat sheet: https://quickref.me/yaml

title: "11ty Sveltia CMS"
description: "Integration of Sveltia CMS with Eleventy and deployment to Netlify"
url: "https://sveltia-cms-11ty.netlify.app"